<?php

namespace App\Enums;

enum ErrorCode: string
{
    case COMPTE_NOT_FOUND = 'COMPTE_NOT_FOUND';
    case COMPTE_STATUS_INVALID = 'COMPTE_STATUS_INVALID';
    case COMPTE_ALREADY_EXISTS = 'COMPTE_ALREADY_EXISTS';
    case COMPTE_CREATION_FAILED = 'COMPTE_CREATION_FAILED';
    case COMPTE_UPDATE_FAILED = 'COMPTE_UPDATE_FAILED';
    case COMPTE_ARCHIVE_FAILED = 'COMPTE_ARCHIVE_FAILED';
    case CLIENT_NOT_FOUND = 'CLIENT_NOT_FOUND';
    case CLIENT_CREATION_FAILED = 'CLIENT_CREATION_FAILED';
    case VALIDATION_ERROR = 'VALIDATION_ERROR';
    case UNAUTHORIZED = 'UNAUTHORIZED';
    case FORBIDDEN = 'FORBIDDEN';
    case INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
    case DATABASE_ERROR = 'DATABASE_ERROR';
    case INVALID_REQUEST = 'INVALID_REQUEST';
}